---
apiVersion: v1
kind: Secret
metadata:
  name: htpass-secret
  namespace: openshift-config
type: Opaque
data:
  htpasswd: b2NwYWRtaW46JDJ5JDA1JEJOV3ZyZnRQLzFscTJkejZlbUxXemVTTTgyVXBTMm9XbGM2bG1LSkJZTUFyV3VJUWxESEEyCm9jcHJlYWRlcjokMnkkMDUkWWZNZmVrUXE3ZExDMGVtOEtEOFVNdTI2dFhpUDV6NUwuZE1jNnQwY1pTejBnSUh3aWhUUWVrCg
